### ISSUE TITLE
Canvas size

### ISSUE THREAD

**Issue by sr-ix** [pxon/pxon-schema#3]
What assumptions does this schema make about the size of the canvas the pixels are rendered on?

Without dimensions provided in the schema, should software parsing the pxon assume infinite canvas or the smallest canvas that fits the drawn pixels?

**Comment by jennschiffer** [comment]
let's say i have 1 pixel drawn on the lower corner of a 500 x 500px canvas (px being display pixels vs. drawing pixels) and each pixel is 1px, the location pxon for that pixel would be like 

`{ "x": 499, "y": 499, "size": 1 }`

so the only assumption made is that the canvas is at least 500 x 500px in the canvas to accommodate that drawing. it totally makes sense that we add some exif data for the intended width and height of the canvas if, for example, that single pixel is supposed to be the center of the whole drawing.
